import { useEffect, useState, type FormEvent, type ReactNode } from 'react';
import { Link, Navigate, useNavigate, useParams } from 'react-router-dom';
import { api, streamChat } from './api';
import { useAuth } from './auth';

export function Protected({ children, role }: { children: ReactNode; role?: string }) {
  const { user } = useAuth();
  if (!user) return <Navigate to="/login" replace />;
  if (role && user.role !== role) return <Navigate to="/dashboard" replace />;
  return children;
}

export function Login() {
  const auth = useAuth(), navigate = useNavigate();
  const [error, setError] = useState('');
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setError(''); const data = new FormData(event.currentTarget); try { await auth.signIn(data.get('role') as any, String(data.get('email')), String(data.get('password'))); navigate('/dashboard'); } catch (err) { setError((err as Error).message); } }
  return <section className="panel narrow"><p className="eyebrow">WELCOME BACK</p><h1>Sign in</h1><form onSubmit={submit}><label>Account type<select name="role"><option value="USER">Customer</option><option value="RESTAURANT">Restaurant</option><option value="DELIVERY_PARTNER">Delivery partner</option></select></label><label>Email<input name="email" type="email" autoComplete="email" required /></label><label>Password<input name="password" type="password" autoComplete="current-password" required /></label>{error && <p className="error">{error}</p>}<button>Sign in</button></form><p>New here? <Link to="/signup">Create an account</Link></p></section>;
}

export function Signup() {
  const auth = useAuth(), navigate = useNavigate(); const [role, setRole] = useState('USER'), [error, setError] = useState('');
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setError(''); const values = Object.fromEntries(new FormData(event.currentTarget).entries()) as Record<string, string>; const latitude = values.latitude, longitude = values.longitude; delete values.latitude; delete values.longitude; try { await auth.signUp({ ...values, role, ...(latitude && longitude ? { location: { latitude: Number(latitude), longitude: Number(longitude) } } : {}) } as any); navigate('/dashboard'); } catch (err) { setError((err as Error).message); } }
  return <section className="panel narrow"><p className="eyebrow">GET STARTED</p><h1>Create account</h1><form onSubmit={submit}><label>Account type<select value={role} onChange={(e) => setRole(e.target.value)}><option value="USER">Customer</option><option value="RESTAURANT">Restaurant</option><option value="DELIVERY_PARTNER">Delivery partner</option></select></label><label>Name<input name="name" required /></label>{role === 'RESTAURANT' && <><label>Restaurant name<input name="restaurantName" required /></label><label>Owner name<input name="ownerName" required /></label><label>FSSAI number<input name="fssaiNumber" /></label></>}{role === 'DELIVERY_PARTNER' && <><label>Vehicle type<input name="vehicleType" required /></label><label>Vehicle number<input name="vehicleNumber" required /></label></>}<label>Email<input name="email" type="email" required /></label><label>Phone<input name="phone" type="tel" required /></label><label>Address<input name="address" required /></label><div className="menu-fields"><label>Latitude<input name="latitude" type="number" step="any" min="-90" max="90" /></label><label>Longitude<input name="longitude" type="number" step="any" min="-180" max="180" /></label></div><label>Password<input name="password" type="password" minLength={10} required /></label>{error && <p className="error">{error}</p>}<button>Create account</button></form></section>;
}

interface Restaurant { _id: string; restaurantName: string; address: string; status: string }
export function Dashboard() {
  const { user, signOut } = useAuth(); const [restaurants, setRestaurants] = useState<Restaurant[]>([]); const [orders, setOrders] = useState<any[]>([]); const [profile, setProfile] = useState<any>(null); const [error, setError] = useState('');
  useEffect(() => {
    if (user?.role === 'USER') api<Restaurant[]>('/restaurants').then(setRestaurants).catch((e) => setError(e.message));
    api<any[]>('/orders').then(setOrders).catch((e) => setError(e.message));
    api<any>('/account/profile').then(setProfile).catch((e) => setError(e.message));
    const refresh = window.setInterval(() => api<any[]>('/orders').then(setOrders).catch((e) => setError(e.message)), 15000);
    return () => window.clearInterval(refresh);
  }, [user]);
  const roleLabel = user?.role === 'USER' ? 'Your next meal starts here.' : user?.role === 'RESTAURANT' ? 'Restaurant workspace' : 'Delivery workspace';
  return <><header className="topbar"><Link className="brand" to="/">Table & Trail</Link><nav><Link to="/dashboard">Dashboard</Link>{user?.role === 'USER' && <Link to="/ai-assistant">AI ordering</Link>}<button className="text-button" onClick={signOut}>Sign out</button></nav></header><main className="workspace"><p className="eyebrow">{user?.role?.replaceAll('_', ' ')}</p><h1>{roleLabel}</h1>{error && <p className="error">{error}</p>}{['RESTAURANT','DELIVERY_PARTNER'].includes(user?.role ?? '') && profile?.status !== 'ACTIVE' && <section className="panel"><h2>Account review in progress</h2><p>Your account is {String(profile?.status ?? 'PENDING').toLowerCase()}. Contact platform support to complete verification. Restaurant publishing and delivery actions are available after approval.</p></section>}{user?.role === 'USER' ? <><h2>Nearby restaurants</h2><div className="cards">{restaurants.map((r) => <article className="card" key={r._id}><h3>{r.restaurantName}</h3><p>{r.address}</p><Link to={`/restaurant/${r._id}`}>View menu →</Link></article>)}</div><h2>Your orders</h2><OrdersList orders={orders} role="USER" onChanged={() => api<any[]>('/orders').then(setOrders).catch((e) => setError(e.message))} /></> : <><h2>Orders</h2><OrdersList orders={orders} role={user?.role} onChanged={() => api<any[]>('/orders').then(setOrders).catch((e) => setError(e.message))} />{user?.role === 'RESTAURANT' && profile?.status === 'ACTIVE' && <MenuEditor />}{user?.role === 'DELIVERY_PARTNER' && profile?.status === 'ACTIVE' && <DeliveryAvailability />}</>}</main></>;
}

export function RestaurantMenu() {
  const { restaurantId = '' } = useParams(); const [menu, setMenu] = useState<any>(null); const [cart, setCart] = useState<Record<string, number>>({}); const [message, setMessage] = useState('');
  useEffect(() => { api<any>(`/restaurants/${restaurantId}/menu`).then(setMenu).catch((e) => setMessage(e.message)); }, [restaurantId]);
  async function placeOrder() { try { const result = await api<any>('/orders', { method: 'POST', body: JSON.stringify({ restaurantId, items: Object.entries(cart).map(([dishId, quantity]) => ({ dishId, quantity })) }) }); setMessage(`Order ${result._id} placed.`); setCart({}); } catch (e) { setMessage((e as Error).message); } }
  return <main className="workspace"><Link to="/dashboard">← Restaurants</Link><h1>Menu</h1>{menu?.items?.map((item: any) => <article className="menu-item" key={item._id}><div><h3>{item.name}</h3><p>{item.description || item.category} · ₹{item.price} · {item.availableQuantity} available</p></div><div className="quantity"><button onClick={() => setCart((c) => ({ ...c, [item._id]: Math.max(0, (c[item._id] ?? 0) - 1) }))}>−</button><span>{cart[item._id] ?? 0}</span><button disabled={cart[item._id] >= item.availableQuantity} onClick={() => setCart((c) => ({ ...c, [item._id]: (c[item._id] ?? 0) + 1 }))}>+</button></div></article>)}{Object.values(cart).some(Boolean) && <button onClick={placeOrder}>Place order</button>}{message && <p role="status">{message}</p>}</main>;
}

function OrdersList({ orders, role, onChanged }: { orders: any[]; role?: string; onChanged?: () => void }) {
  async function transition(orderId: string, status: string, estimatedPreparationMinutes?: number) { try { await api(`/orders/${orderId}/transition`, { method: 'POST', body: JSON.stringify({ status, estimatedPreparationMinutes }) }); onChanged?.(); } catch (error) { window.alert((error as Error).message); } }
  async function assign(orderId: string) { try { await api(`/orders/${orderId}/assign-delivery`, { method: 'POST' }); onChanged?.(); } catch (error) { window.alert((error as Error).message); } }
  async function fail(orderId: string) { const reason = window.prompt('Describe the issue'); if (reason) { try { await api(`/orders/${orderId}/failures`, { method: 'POST', body: JSON.stringify({ reason }) }); onChanged?.(); } catch (error) { window.alert((error as Error).message); } } }
  return <div className="cards">{orders.map((o) => <article className="card" key={o._id}><h3>Order {o._id.slice(-7)}</h3><p>{o.status.replaceAll('_', ' ')} · ₹{o.total}</p>{o.restaurantId?.restaurantName && <p>Restaurant: {o.restaurantId.restaurantName}</p>}{role !== 'USER' && o.userId?.name && <p>Customer: {o.userId.name} · {o.userId.phone}</p>}{role === 'DELIVERY_PARTNER' && <><p>Pickup: {o.restaurantId?.address ?? 'Restaurant address unavailable'}</p><p>Deliver to: {o.deliveryAddress}</p>{o.estimatedReadyAt && <p>Estimated ready: {new Date(o.estimatedReadyAt).toLocaleTimeString()}</p>}</>}<p>{o.items?.map((i: any) => `${i.quantity} × ${i.dishName}`).join(', ')}</p>{o.retry && <small>Retries · cooking {o.retry.cooking} · delivery {o.retry.delivery}</small>}{role === 'USER' && o.estimatedReadyAt && <p>Estimated ready: {new Date(o.estimatedReadyAt).toLocaleTimeString()}</p>}{role === 'USER' && o.status === 'PENDING_RESTAURANT' && <button className="secondary" onClick={() => void transition(o._id, 'CANCELLED')}>Cancel order</button>}{role === 'RESTAURANT' && <div className="actions">{o.status === 'PENDING_RESTAURANT' && <><button onClick={() => { const value = Number(window.prompt('Preparation time in minutes', '20')); if (value > 0) void transition(o._id, 'RESTAURANT_ACCEPTED', value); }}>Accept</button><button className="secondary" onClick={() => void transition(o._id, 'RESTAURANT_REJECTED')}>Reject</button></>}{o.status === 'RESTAURANT_ACCEPTED' && <button onClick={() => void transition(o._id, 'PREPARING')}>Start preparing</button>}{o.status === 'PREPARING' && <button onClick={() => void transition(o._id, 'READY_FOR_PICKUP')}>Ready for pickup</button>}{o.status === 'READY_FOR_PICKUP' && <button onClick={() => void assign(o._id)}>Assign delivery</button>}{['PREPARING','RESTAURANT_ACCEPTED'].includes(o.status) && <button className="secondary" onClick={() => void fail(o._id)}>Report cooking issue</button>}</div>}{role === 'DELIVERY_PARTNER' && <div className="actions">{o.status === 'DELIVERY_ASSIGNED' && <button onClick={() => void transition(o._id, 'DELIVERY_ACCEPTED')}>Accept delivery</button>}{o.status === 'DELIVERY_ACCEPTED' && <button onClick={() => void transition(o._id, 'PICKED_UP')}>Picked up</button>}{o.status === 'PICKED_UP' && <button onClick={() => void transition(o._id, 'OUT_FOR_DELIVERY')}>Out for delivery</button>}{o.status === 'OUT_FOR_DELIVERY' && <><button onClick={() => void transition(o._id, 'DELIVERED')}>Delivered</button><button className="secondary" onClick={() => void fail(o._id)}>Report delivery issue</button></>}</div>}</article>)}{orders.length === 0 && <p>No orders yet.</p>}</div>;
}

function DeliveryAvailability() {
  const [available, setAvailable] = useState(false), [message, setMessage] = useState('');
  useEffect(() => { api<{ isAvailable: boolean }>('/delivery/availability').then((result) => setAvailable(result.isAvailable)).catch((error) => setMessage((error as Error).message)); }, []);
  async function toggle() { try { const result = await api<{ isAvailable: boolean }>('/delivery/availability', { method: 'PATCH', body: JSON.stringify({ available: !available }) }); setAvailable(result.isAvailable); setMessage(result.isAvailable ? 'You are available for assignments.' : 'You are paused.'); } catch (error) { setMessage((error as Error).message); } }
  return <section className="panel"><h2>Delivery availability</h2><p>Current setting: {available ? 'Available' : 'Paused'}</p><button onClick={toggle}>Turn {available ? 'off' : 'on'} availability</button>{message && <p role="status">{message}</p>}</section>;
}

function MenuEditor() {
  const [items, setItems] = useState([{ name: '', category: 'Main Course', price: '', availableQuantity: '' }]), [status, setStatus] = useState('');
  function update(index: number, key: string, value: string) { setItems((all) => all.map((item, i) => i === index ? { ...item, [key]: value } : item)); }
  async function publish(event: FormEvent) { event.preventDefault(); try { await api('/restaurant/menu', { method: 'PUT', body: JSON.stringify({ published: true, items: items.filter((item) => item.name).map((item) => ({ ...item, price: Number(item.price), availableQuantity: Number(item.availableQuantity) })) }) }); setStatus('Menu published.'); } catch (error) { setStatus((error as Error).message); } }
  return <section className="panel menu-editor"><h2>Menu management</h2><form onSubmit={publish}>{items.map((item, index) => <div className="menu-fields" key={index}><input aria-label="Dish name" placeholder="Dish name" value={item.name} onChange={(e) => update(index, 'name', e.target.value)} required /><input aria-label="Category" placeholder="Category" value={item.category} onChange={(e) => update(index, 'category', e.target.value)} required /><input aria-label="Price" type="number" min="0" placeholder="Price" value={item.price} onChange={(e) => update(index, 'price', e.target.value)} required /><input aria-label="Quantity" type="number" min="0" placeholder="Quantity" value={item.availableQuantity} onChange={(e) => update(index, 'availableQuantity', e.target.value)} required /></div>)}<div className="actions"><button type="button" className="secondary" onClick={() => setItems((all) => [...all, { name: '', category: 'Main Course', price: '', availableQuantity: '' }])}>Add item</button><button>Publish menu</button></div></form>{status && <p role="status">{status}</p>}</section>;
}

export function Assistant() {
  const [messages, setMessages] = useState<{ role: string; content: string }[]>([]), [text, setText] = useState(''), [busy, setBusy] = useState(false), [error, setError] = useState(''), [sessionId, setSessionId] = useState<string>();
  async function send(event: FormEvent) { event.preventDefault(); const userText = text.trim(); if (!userText || busy) return; setText(''); setMessages((m) => [...m, { role: 'user', content: userText }, { role: 'assistant', content: '' }]); setBusy(true); setError(''); try { const response = await streamChat(userText, sessionId, (token) => setMessages((m) => { const copy = [...m]; copy[copy.length - 1] = { role: 'assistant', content: copy[copy.length - 1].content + token }; return copy; })); setSessionId(response.sessionId); } catch (e) { setError((e as Error).message); setMessages((m) => m.slice(0, -1)); } finally { setBusy(false); } }
  function speak() { const browser = window as Window & { SpeechRecognition?: new () => any; webkitSpeechRecognition?: new () => any }; const Recognition = browser.SpeechRecognition ?? browser.webkitSpeechRecognition; if (!Recognition) { setError('Speech recognition is not supported by this browser.'); return; } const recognition = new Recognition(); recognition.lang = 'en-IN'; recognition.onresult = (event: any) => setText(event.results[0][0].transcript); recognition.start(); }
  return <main className="workspace chat"><Link to="/dashboard">← Dashboard</Link><p className="eyebrow">AI ORDERING</p><h1>What are you craving?</h1><div className="transcript" aria-live="polite">{messages.length === 0 && <p>Tell me what you’d like to order. I’ll check real menu availability before placing anything.</p>}{messages.map((m, i) => <p className={`bubble ${m.role}`} key={i}>{m.content}</p>)}{busy && <p className="bubble assistant">Checking…</p>}</div>{error && <p className="error">{error}</p>}<form onSubmit={send} className="chat-form"><input value={text} onChange={(e) => setText(e.target.value)} placeholder="Try: two chicken biryanis" aria-label="Your message" /><button type="button" className="secondary" onClick={speak}>Voice</button><button disabled={busy}>Send</button></form></main>;
}
